title: <p align="center"> Chaitra Mokhasi</p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://github.com/ChaitraMokhasi">GitHub</a>
  
  <br>   
  I'm working Machine learningproblems.
  <br>
  </p>



theme: jekyll-theme-minimal
